version: '3.8'
services:
    uprun_puma:
      build:
        context: ./
        dockerfile: ./containers/Dockerfile
      volumes:
        - ./build:/var/www # persist builds
      networks:
        - web_network
      restart: always
    comiket_csv_nginx:
      build:
        context: ./
        dockerfile: ./containers/Dockerfile
      networks:
        - web_network
      volumes_from:
        - comiket_csv_nginx
      depends_on:
        - comiket_csv_nginx
      restart: always

networks:
  web_network:
    external: true
