version: '3.8'
services:
    comiket_csv:
      build:
        context: ./
        dockerfile: ./containers/Dockerfile
      volumes:
        - ./build:/var/www # persist builds
      networks:
        - web_network
      restart: always

networks:
  web_network:
    external: true
